<a href="https://colab.research.google.com/github/space-32/Python/blob/main/MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# It is a computer vision problem and optical character problem
# Computer vision deals with images
# NLP is natural language processing
# In deep learning there are 2 majors: 1. Computer Vision and 2.NLP
# In MNIST there are only numbers

In [ ]:
import sklearn


In [ ]:
sklearn.__version__

'1.2.2'

In [ ]:
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np
import pandas as pd

In [ ]:
mnist = fetch_openml('mnist_784', version=1)
mnist.keys()
# Extract data and target labels
X, y = mnist['data'], mnist['target']

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [ ]:
mnist.values()

dict_values([       pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10

In [ ]:
mnist.keys()

dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

In [ ]:
y = y.astype(np.int8)  # Convert labels to integers
#Datatype of y is int64 but we are reducing it to int8

# Print the shape of data
print(f"Shape of X: {X.shape}")
print(f"Shape of y: {y.shape}")

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training set size: {X_train.shape[0]}")
print(f"Test set size: {X_test.shape[0]}")


Shape of X: (70000, 784)
Shape of y: (70000,)
Training set size: 56000
Test set size: 14000


In [ ]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train.astype(np.float64))
X_test_scaled=scaler.transform(X_test.astype(np.float64))

In [ ]:
log_reg = LogisticRegression(max_iter=1000, solver='lbfgs', multi_class='multinomial')
log_reg.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000, multi_class='multinomial')

In [ ]:
y_pred = log_reg.predict(X_test) #we get predicted values
accuracy = accuracy_score(y_test, y_pred) #getting an accuracy between the original and predicted values
print(f"Accuracy: {accuracy * 100:.2f}%")

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
#Confusion matrix dimension is large bcz we are predicting the no. is 0 or not 0, it is 1 or not 1 and so on


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


Accuracy: 83.36%
Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.96      0.94      1343
           1       0.97      0.88      0.92      1600
           2       0.95      0.77      0.85      1380
           3       0.86      0.88      0.87      1433
           4       0.87      0.91      0.89      1295
           5       0.97      0.24      0.39      1273
           6       0.92      0.93      0.93      1396
           7       0.97      0.84      0.90      1503
           8       0.51      0.96      0.67      1357
           9       0.80      0.91      0.85      1420

    accuracy                           0.83     14000
   macro avg       0.87      0.83      0.82     14000
weighted avg       0.87      0.83      0.83     14000

Confusion Matrix:
[[1295    1    4    2    7    1   11    3   16    3]
 [   0 1415    3   13    2    0    2    3  158    4]
 [  15   15 1060   31   30    0   33   18  156   22]
 [  10    5   14 1254   