<a href="https://colab.research.google.com/github/space-32/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #uses of alias

arr= np.array([1,2,3,4,5])
print(arr)
print(type(arr)) #type of array
print(arr.shape) #dimension of array
print(arr.dtype) #dtype tells what type of values are stored

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
int64


In [ ]:
print(np.__version__) #gives the version of np

1.25.2


In [ ]:
arr=np.array(42) #arr variable is overriddening the previous arr
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)

42
<class 'numpy.ndarray'>
()
int64


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print(arr.shape) # shapr= 2 rows and 3 cols
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
int64


In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
(2, 2, 3)
int64


In [ ]:
arr= np.array([1,2,3,4])
print(arr[2]+arr[3])


7


In [ ]:
arr= np.array([1,2,3,4,5,6,7])
print(arr[1:5]) #this is known as slicing, in which it will take the element of index 1 but exclusive of index 5
print(arr[:3]) # will print the elements from index 0 to mentioned index 3

[2 3 4 5]
[1 2 3]


In [ ]:
#we can create array using other methods of numpy such as np.zeros(), np.ones(),np.arange()
m=np.arange(10)
print(m)

y=np.zeros(5)
print(y)


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0.]


In [ ]:
#Numpy-ndarray basic operations
a=np.array([2,3,4],int)

print(a.sum()) #will sum
print(a.prod()) #will give product
print(a.mean()) #will give mean
print(a.std())  #will give standard deviation
print(a.min()) #will give minimum
print(a.max()) #will give maximum

9
24
3.0
0.816496580927726
2
4


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.transpose()) #will give transpose
np.invert(a) #will give inverse

[[1 4 7]
 [2 5 8]
 [3 6 9]]


array([[ -2,  -3,  -4],
       [ -5,  -6,  -7],
       [ -8,  -9, -10]])